In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import tensorflow as tf

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv")

In [ ]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [ ]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [ ]:
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=40)

In [ ]:
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.transform(x_test)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(64,activation='relu',input_shape=(13,)))
model.add(Dense(32,activation='relu',))
model.add(Dense(1))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

In [ ]:
model.fit(
    x_train,
    y_train,
    epochs=100,
    batch_size=16
)

Epoch 1/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 552.9088 - mae: 21.7975
Epoch 2/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 460.4078 - mae: 19.6140
Epoch 3/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 316.2799 - mae: 15.7805
Epoch 4/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 153.7281 - mae: 10.4138
Epoch 5/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.8123 - mae: 6.5841
Epoch 6/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 42.6478 - mae: 4.8934
Epoch 7/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 30.8660 - mae: 4.0152
Epoch 8/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25.7487 - mae: 3.6207
Epoch 9/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 23.5865 - mae: 3.3909
Epoch 10/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21.8764 - mae: 3.2901
Epoch 11/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.5728 - mae: 3.1804
Epoch 12/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.6178 - mae: 3.0958
Epoch 13/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.0704 - mae: 3.0941
Epoch 14/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.9404 - mae: 2.9817
Epoch 15/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.3598 - mae: 2.8977
Epoch 16/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.7322 - mae: 2.8352
Epoch 17/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.0976 - mae: 2.7857
Epoch 18/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.5375 - mae: 2.7087
Epoch 19/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15.1618 - mae: 2.6980
Epoch 20/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.6163 - mae: 2.6217
Epoch 21/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2325 - mae: 2.5993
Epoch 22/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.8695 - mae: 2.5644
Epoch 23/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13.4377 - mae: 2.5264
Epoch 24/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.0634 - mae: 2.4942
Epoch 25/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.9353 - mae: 2.4428
Epoch 26/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.5119 - mae: 2.4463
Epoch 27/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.4781 - mae: 2.4413
Epoch 28/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12.1684 - mae: 2.3839
Epoch 29/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.1204 - mae: 2.4007
Epoch 30/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.8681 - mae: 2.3495
Epoch 31/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.8686 - mae: 2.3655
Epoch 32/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.4766 - mae: 2.3487
Epoch 33/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.2399 - mae: 2.2994
Epoch 34/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.9497 - mae: 2.2714
Epoch 35/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.8474 - mae: 2.2555
Epoch 36/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.8132 - mae: 2.2435
Epoch 37/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.6191 - mae: 2.2697
Epoch 38/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.6795 - mae: 2.2352
Epoch 39/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.3797 - mae: 2.2191
Epoch 40/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.3302 - mae: 2.2009
Epoch 41/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.2582 - mae: 2.2238
Epoch 42/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9208 - mae: 2.1506
Epoch 43/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9597 - mae: 2.1524
Epoch 44/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.8269 - mae: 2.1529
Epoch 45/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.6527 - mae: 2.1538
Epoch 46/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.5754 - mae: 2.1281
Epoch 47/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.4578 - mae: 2.1206
Epoch 48/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.4568 - mae: 2.1724
Epoch 49/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.4647 - mae: 2.1153
Epoch 50/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.1959 - mae: 2.0785
Epoch 51/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.4729 - mae: 2.1611
Epoch 52/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.2384 - mae: 2.1056
Epoch 53/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.1787 - mae: 2.1164
Epoch 54/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.9576 - mae: 2.1092
Epoch 55/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.8649 - mae: 2.0540
Epoch 56/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.5994 - mae: 2.0296
Epoch 57/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.4483 - mae: 2.0041
Epoch 58/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.4444 - mae: 2.0292
Epoch 59/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.3805 - mae: 1.9875
Epoch 60/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4172 - mae: 2.0431
Epoch 61/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3640 - mae: 2.0020
Epoch 62/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.3512 - mae: 1.9904
Epoch 63/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3474 - mae: 2.0551
Epoch 64/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2543 - mae: 1.9931
Epoch 65/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.1526 - mae: 1.9759
Epoch 66/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.8684 - mae: 1.9647
Epoch 67/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.8319 - mae: 1.9488
Epoch 68/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.7355 - mae: 1.9486
Epoch 69/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.7159 - mae: 1.9330
Epoch 70/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.5270 - mae: 1.9343
Epoch 71/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8249 - mae: 1.9624
Epoch 72/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.5126 - mae: 1.9275
Epoch 73/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4340 - mae: 1.9186
Epoch 74/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.2306 - mae: 1.8882
Epoch 75/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.2946 - mae: 1.9062
Epoch 76/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.1678 - mae: 1.8780
Epoch 77/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.2937 - mae: 1.8903
Epoch 78/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.0662 - mae: 1.8750
Epoch 79/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.0459 - mae: 1.8573
Epoch 80/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.0142 - mae: 1.8778
Epoch 81/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8885 - mae: 1.8589
Epoch 82/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7625 - mae: 1.8506
Epoch 83/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8257 - mae: 1.8447
Epoch 84/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7265 - mae: 1.8409
Epoch 85/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7684 - mae: 1.8312
Epoch 86/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8319 - mae: 1.8586
Epoch 87/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4509 - mae: 1.8146
Epoch 88/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5935 - mae: 1.8315
Epoch 89/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5750 - mae: 1.8094
Epoch 90/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6559 - mae: 1.8372
Epoch 91/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3168 - mae: 1.7829
Epoch 92/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2887 - mae: 1.7954
Epoch 93/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3268 - mae: 1.7760
Epoch 94/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3169 - mae: 1.8031
Epoch 95/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1444 - mae: 1.7728
Epoch 96/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0988 - mae: 1.7528
Epoch 97/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9286 - mae: 1.7484
Epoch 98/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.8782 - mae: 1.7316
Epoch 99/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9018 - mae: 1.7322
Epoch 100/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0035 - mae: 1.7669

In [ ]:
y_pred = model.predict(x_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score

mse = mean_squared_error(y_test, y_pred)
r2square = r2_score(y_test,y_pred)

print("MSE:", mse)
print("R2 Square: ",r2square)

MSE: 8.962158990584303
R2 Square:  0.9209874001334596